// cleanup-repo.js
// Cleans up accumulated .bak files and patch scripts, and prevents future commits

const fs = require("fs");
const path = require("path");

// 1) Update .gitignore
console.log(">>> Updating .gitignore");
const gi = ".gitignore";
const existing = fs.existsSync(gi) ? fs.readFileSync(gi, "utf8") : "";
const additions = `

# Auto-generated by patch scripts (Claude assistant)
*.bak
patch-*.js
patch-*.py
continue-patch-*.js
hotfix-*.js
cleanup-repo.js
`;

if (existing.includes("*.bak") && existing.includes("patch-*.js")) {
  console.log("  [skip ] .gitignore already configured");
} else {
  fs.writeFileSync(gi, existing.replace(/\n+$/, "") + additions, "utf8");
  console.log("  [done ] .gitignore updated");
}

// 2) Recursively delete all *.bak files
console.log("\n>>> Deleting .bak files");
let bakCount = 0;

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === ".next" || entry.name === ".git") continue;
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(p);
    } else if (entry.name.endsWith(".bak")) {
      fs.unlinkSync(p);
      console.log(`  [del ] ${p}`);
      bakCount++;
    }
  }
}
walk(".");
console.log(`  ${bakCount} .bak file(s) deleted`);

// 3) Delete root-level patch scripts
console.log("\n>>> Deleting patch scripts at root");
const patterns = [
  /^patch-.*\.js$/,
  /^patch-.*\.py$/,
  /^continue-patch-.*\.js$/,
  /^hotfix-.*\.js$/,
];
let scriptCount = 0;
for (const entry of fs.readdirSync(".", { withFileTypes: true })) {
  if (entry.isFile() && patterns.some((p) => p.test(entry.name))) {
    fs.unlinkSync(entry.name);
    console.log(`  [del ] ${entry.name}`);
    scriptCount++;
  }
}
console.log(`  ${scriptCount} script(s) deleted`);

// 4) Delete weird "master" file if exists (from earlier bad commit)
if (fs.existsSync("master") && fs.statSync("master").isFile()) {
  fs.unlinkSync("master");
  console.log("\n>>> Deleted stray 'master' file");
}

console.log("\n[OK] Cleanup complete.\n");
console.log("Next:");
console.log("  git add -A");
console.log("  git commit -m \"chore: clean up .bak files and patch scripts\"");
console.log("  git push origin master");
console.log("\nNOTE: this script self-deletes after the commit (it's also in .gitignore).");
